conversation/urls.py
from django.urls import path
from conversation import views

app_name = 'conversation'

urlpatterns = [
    path("", views.inbox, name="inbox"),
    path("show/<int:conversation_id>/", views.show, name="show"),
    path("new/<int:item_id>/", views.new_conversation, name="new"),
]

core/urls.py
from django.urls import path
from core.views import index, contact, signup
from django.contrib.auth import views
from core.forms import LoginForm

app_name = "core"

urlpatterns = [
    path('', index, name="index"),
    path('contact/', contact, name="contact"),
    path('signup/', signup, name="signup"),
    path('login/', views.LoginView.as_view(authentication_form=LoginForm,
         template_name="login.html"), name="login"),
]

dashboard/urls.py
from django.urls import path
from dashboard.views import index


app_name = "dashboard"

urlpatterns = [
    path("", index, name="index")
]

item/urls.py
from django.urls import path
from item.views import show, create_item, delete_item, edit_item, items

app_name = "item"

urlpatterns = [
    path("", items, name="items"),
    path("create_item/", create_item, name="create_item"),
    path("<int:id>/", show, name="show"),
    path("delete/<int:id>/", delete_item, name="delete"),
    path("edit/<int:id>/", edit_item, name="edit"),
]

pebble/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("core.urls")),
    path("item/", include("item.urls")),
    path("dashboard/", include("dashboard.urls")),
    path("conversation/", include("conversation.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Your username",
        "class": "w-full py-4 px-6 rounded-xl"
    }))

    email = forms.EmailField(widget=forms.EmailInput(attrs={
        "placeholder": "Your email",
        "class": "w-full py-4 px-6 rounded-xl"
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Your password",
        "class": "w-full py-4 px-6 rounded-xl"
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Repeat password",
        "class": "w-full py-4 px-6 rounded-xl",
    }))


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('email', 'password')

    username = forms.CharField(widget=forms.TextInput(attrs={
        "placeholder": "Your username",
        "class": "w-full py-4 px-6 rounded-xl"
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        "placeholder": "Your password",
        "class": "w-full py-4 px-6 rounded-xl"
    }))

core/views.py
from django.shortcuts import render, redirect
from item.models import Item, Category
from core.forms import SignUpForm


def index(request):
    items = Item.objects.filter(is_sold=False)[:6]
    categories = Category.objects.all()

    return render(request, "index.html", {
        "items": items,
        "categories": categories,
    })


def contact(request):
    return render(request, "contact.html")


def signup(request):

    if request.method == "POST":
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect(to="core:login")
    else:
        form = SignUpForm()

    return render(request, "signup.html", {
        "form": form
    })

core/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.tailwindcss.com"></script>
    <title>
        {% block title %}  {% endblock %} | Pebble
    </title>
</head>
<body>
    <nav class="py-6 px-6 flex justify-between items-center border-b border-gray-200">
        <a href="{% url 'core:index' %}" class="text-xl font-semibold">Pebble</a>
        <div class="space-x-6">
            <a href="{% url 'item:create_item' %}" class="text-lg font-semibold hover:text-gray-500">New item</a>
            <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>
            
            {% if not request.user %}
                <a href="{% url 'core:signup' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign Up</a>
                <a href="{% url 'core:login' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Login</a>
            {% else %}
                <a href="{% url 'conversation:inbox' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                <a href="{% url 'dashboard:index' %}" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
            {% endif %}

            
        </div>
    </nav>
    <div class="px-6 py-6">
        {% block content %}
        {% endblock %}
    </div>

    <footer class="py-6 px-6 flex justify-between bg-gray-800">
        <div class="w-2/3 pr-10">
            <h3 class="mb-5 font-semibold text-gray-400">About</h3>

            <p class="text-lg text-gray-500">Lorem ipsum bla bla bla. Lorem ipsum bla bla bla. Lorem ipsum bla bla bla.</p>
        </div>

        <div class="w-1/3">
            <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

            <ul class="space-y-2">
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                <li><a href="{% url 'core:contact' %}" class="text-lg text-teal-500 hover:text-teal-700">Contact</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Term of use</a></li>
            </ul>
        </div>
    </footer>
</body>
</html>

core/templates/contact.html
{% extends 'index.html' %}

{% block title %}
Contact
{% endblock title %}

{% block content %}
<h1>content contact</h1>
{% endblock content %}

core/templates/index.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Newest items</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for item in items %}
                <div>
                    <a href="{% url 'item:show' item.id %}">
                        <div>
                            <img src="{{ item.image.url }}" class="rounded-t-xl">
                        </div>

                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ item.name }}</h2>
                            <p class="text-gray-500">Price: {{ item.price }}</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
                <div>
                    <a href="#">
                        <div class="p-6 bg-white rounded-b-xl">
                            <h2 class="text-2xl">{{ category.name }}</h2>
                            <p class="text-gray-500">{{ category.items.count }} items</p>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

core/templates/login.html
{% extends 'base.html' %}


{% block title %}Log In{% endblock title %}

{% block content %}

<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log In</h1>
    <form method="post" action=".">
        {% csrf_token %}


        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>


        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}


        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>

{% endblock content %}

core/templates/signup.html
{% extends 'base.html' %}


{% block title %}Sign Up{% endblock title %}

{% block content %}

<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>
    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Email</label><br>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat password</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}


        <button class="py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>
</div>

{% endblock content %}